name: Generate docker image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        uses: actions/checkout@v4
      -
        name: Set env
        run: echo "PYTHON_VERSION=$(cat ./chatbot/.python-version)" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:chatbot"
          push: true
          tags: ghcr.io/sogokato/shigeru-gpt/chatbot:latest
          build-args: PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          platforms: linux/amd64,linux/arm64
